version: '3.7'
services:

  frontend:
    image: frontend-image
    ports:
      - 8888:8000  

  db:
    image: postgres:15
    container_name: db_app
    ports:
      - 1221:5432  
    env_file:
      - .env

  backend:
    build:
      context: .
    env_file:
      - .env
    container_name: fastapi_app
    ports:
      - 9999:8000 
    depends_on:
      - db
