
version: '3'

x-env-variables: &env-variables
  POSTGRES_USER: "postgres"
  POSTGRES_PASSWORD: "9792amina"
  POSTGRES_DB: "egov"
  DATABASE_URL: "postgresql://postgres:9792amina@host.docker.internal:5432/egov"

services:

  backend:
    container_name: fastapi_app
    build:
      context: ./backend
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment: 
      <<: *env-variables
    # networks:
    #   - egov

  db:
    container_name: postgresql_db
    image: postgres
    ports:
      - 5433:5432
    environment: 
      <<: *env-variables

  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    # networks:
    #   - egov

# networks:
#   egov:
#     driver: bridge