
version: '3'

services:
  postgres:
    container_name: db_app
    build:
      context: ./backend/dbase
    ports:
      - "5433:5432"


  backend:
    container_name: fastapi_app
    build:
      context: ./backend
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - postgres

  frontend:
    build:
      context: ./frontend
    ports:
      - "80:3000"
    depends_on:
      - backend

