
version: '3'

x-env-variables: &env-variables
  POSTGRES_USER: "postgres"
  POSTGRES_PASSWORD: "601246"
  POSTGRES_DB: "egov"
  DATABASE_URL: "postgresql://postgres:601246@host.docker.internal:5432/egov"

services:

  db:
    container_name: postgresql_db
    image: postgres
    ports:
      - 5433:5432
    environment: 
      <<: *env-variables

  backend:
    container_name: fastapi_app
    environment: 
      <<: *env-variables
    build:
      context: ./backend
    ports:
      - "8000:8000"
    command: ["/app/docker/app.sh"]
    depends_on:
      - db
  
    # networks:
    #   - egov

  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    # networks:
    #   - egov

# networks:
#   egov:
#     driver: bridge