version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile  # Path to your Dockerfile for the FastAPI application
    command: uvicorn backend.main:app --host 0.0.0.0 --port 8000 --reload
    ports:
      - "8000:8000"
    depends_on:
      - database

  tests:
    build:
      context: .
      dockerfile: Dockerfile.tests  # Path to your Dockerfile for tests
    command: ["pytest", "test_b"]  # Adjust the path based on your test directory
    depends_on:
      - app

  database:
    image: postgres:latest
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
